#add_newline = false

[line_break]
#disabled = true

[directory]
truncation_length = 8

[golang]
symbol = "î˜§ "

[aws]
format = "on [$symbol$region]($style) "
style = "bold blue"
symbol = "îŒ½ "
#displayed_items = "region"

[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"

[kubernetes]
symbol = "â›µ "
style = "blue"
disabled = true
#disabled = false

[git_branch]
symbol = "ï˜ "

[git_status]
conflicted = "ğŸ³"
#ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
stashed = "ğŸ“¦"
staged.value = "++"
staged.style = "green"
staged.count.enabled = true
staged.count.style = "green"
#renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
modified.count = true
#show_sync.count = true
#modified = "ğŸ“"
#untracked = "ğŸ¤·â€"

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "ï€“ "
#symbol = "ğŸ¦€"
